version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
        - "8082:8081"
