name: Run Docker Container On Production

on:
  push:
    branches:
      - production

jobs:
  build-sony:
    runs-on: [sony]
   

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: docker --version

    - name: Run Docker Container
      run: |
        docker stop springweb || true
        docker rm springweb || true
        docker rmi springweb:latest || true
        docker build -t springweb:latest -f Dockerfile .
        docker run -d -p 8082:8081 --name springweb --env MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} --env MYSQL_USER=${{ secrets.MYSQL_USER }} springweb:latest

  build-aws:
    runs-on: [aws]
   

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: docker --version

    - name: Run Docker Container
      run: |
        docker stop springweb || true
        docker rm springweb || true
        docker rmi springweb:latest || true
        docker build -t springweb:latest -f Dockerfile .
        docker run -d -p 8082:8081 --name springweb --env MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} --env MYSQL_USER=${{ secrets.MYSQL_USER }} springweb:latest
